Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -81,4 +81,4 @@ jobs:
             echo "Checking container status..."
             docker ps
             echo "Health check..."
-            curl -f http://localhost || { echo "Health check failed"; exit 1; }
+            curl -f http://localhost || { echo "Health check failed"; exit 1;}
